title: <p align="center"> Vedant Parnaik </p>

logo: "/images/IMG_4993_cropped.jpg?raw=true"

description:
  <p align="center">
  SWE | Data Scientist <br>
  <a href="pdf/vedant_parnaik__.pdf" target="_blank">Resume</a> |
  <a href="https://www.linkedin.com/in/vedantparnaik/" target="_blank">LinkedIn</a> |
  <a href="https://github.com/vedantparnaik" target="_blank">GitHub</a>
  </p>
  
  <p align="justify">
  I am a recent grad with a background in Software engineering, skilled in building scalable applications and pipelines using AWS (EC2, BedRock, SageMaker), Docker, and CI/CD.
  </p>
  
theme: jekyll-theme-minimal
google_analytics: G-03W5FBFF2W # Google Analytics tracking ID
